[package]
name = "nineprofs-document-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
nineprofs-api-types = { path = "../nineprofs-api-types" }
nineprofs-common = { path = "../nineprofs-common" }
nineprofs-documents = { path = "../nineprofs-documents" }
nineprofs-realtime = { path = "../nineprofs-realtime" }
nineprofs-tools = { path = "../nineprofs-tools" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
