export type {
  ApprovedDocumentChangeSet,
  DocumentAuthority,
  DocumentChange,
  DocumentChangeSet,
  DocumentChangeSetId,
  DocumentChangeSetBase,
  DocumentId,
  DocumentMutationAppliedResult,
  DocumentInspection,
  DocumentInspectionRequest,
  DocumentInspector,
  DocumentMutationGateway,
  DocumentMutationResult,
  DocumentVersion,
  DocumentVersionConflictResult,
  GenOfficeActiveDocumentAuthority,
  ProposedDocumentChangeSet,
  RejectedDocumentChangeSet,
} from './types'
