[package]
name = "nineprofs-research"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
nineprofs-api-types = { path = "../nineprofs-api-types" }
nineprofs-common = { path = "../nineprofs-common" }
nineprofs-realtime = { path = "../nineprofs-realtime" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true

[dev-dependencies]
nineprofs-db = { path = "../nineprofs-db" }
serde_yaml = "0.9"
tokio.workspace = true
